### ISSUE TITLE
Create Mockups

### ISSUE THREAD

**Issue by rronakk** [rronakk/ynah#1]

**Comment by seakim** [comment]
Find your lunch

—— first page —— intro page

Are you frustrated and exhausted of deciding what to eat for lunch?  And you work in the city?  
C’mon!! The city has Everything, you just can’t find the right thing!!!

Just tell me what you want, and I will find it for you.
And one of your biggest struggle of the day will be gone.

user input:
(default: main meal / can choose appetizers/sides) ( what do you want? e.g> chicken / salad / burger / Italian ) ( price range 8? 10? 12? 15?) (delivery: yes/no)
maybe embed a video in background
—————————
—— second page —— 
user input: (push to the top)
(default: main meal / can choose appetizers/sides) ( what do you want? e.g> chicken / salad / burger / Italian ) ( price range 8? 10? 12? 15?) (delivery: yes/no)

show a list of randomized items (maybe 6?)
if user does not want any, pull 6 more from (collection =- first pull)
prepend the new list to the first page, move the first 6 to 2nd page

list item from api search with:
	item name / price
	restaurant name,
	restaurant rate (from yelp),
	distance from you / delivery (from yelp),
	couple reviews about the restaurant (from yelp)

—— advanced ——
user login
after user pick an item, it asks user if he want to try it out (true / false)
if tried is true, user can rate on the food with option of comment
e.g>
	How did you like it?
		food rate (0 - 5)

user can have record of the tried foods and restaurants
	restaurant A (4 *) - average stars
		- item A (3.5 *) - from the user input
		- item B (4.5 *)
	restaurant B (2.5 *)
		- item A (2.5 *)

user can use the record for future reference
we can collect the user rate and review on each item of the restaurants 

—— bonus ——
Make it yourself!! 
use another API to find the (general) ingredients after user chooses an item 
after user chooses an item, it shows an option to see general ingredient to make it
e.g> it shows:
	ingredients / amount / calories / protein / fat / carb / etc…
