### ISSUE TITLE
Write up project description

### ISSUE THREAD

**Issue by rronakk** [rronakk/ynah#2]

**Comment by kb2232** [comment]
**Team Members**:
 1. Kunle Babatunde
 2. Michael Kim
 3. Sean Kim
 4. Ronak Ray

Project Title:  **_Event Scheduler_**
The goal with this project is to create a component that will be a add-on to our main project, which is to come. We have decided to create an event scheduler to book and maintain events for clients who register on our app. The event scheduler will boast multiple API's, such as google calendar API, tawilio api and/or others. We will use firebase to store basic information and, for now, to handle authentication, where clients will be asked to login in with google or facebook. The features on this app will be: 

1. schedule an event
2. sending text
3. postponing notifications
4. accepting notifications 
5. declining notifications

**Comment by rronakk** [comment]
I dont think we should mention about Add-on thing, Its just for us to know.

We can say features : 

### Scheduling : 
* Create Event
* Edit Events 
* View Scheduled events.
* Add Notes per events.

### Notification : 
* Event confirmation notification (Email / Text)
* Cancellation notification
* Reminder notification (this would be tough to implement without a server)

We should realize whatever we are doing is only at client side ? so some things would be limited.
We should define our requirement taking that into consideration, and not overcommit on things.

**Comment by kb2232** [comment]
Team Members:
**Kunle Babatunde**
1. Michael Kim
2. Sean Kim
3. Ronak Ray

Project Title: **_Event Scheduler_**
    We have decided to create an event scheduler to book and maintain events for clients who register on our app. The event scheduler will boast multiple API's, such as google calendar API, tawilio api and/or others. We will use firebase to store basic information and, for now, to handle authentication, where clients will be asked to login in with google or facebook. 
The features on this app will **schedule** and **notify**:

**Scheduling :**

- Create Event
- Edit Events
- View Scheduled events.
- Add Notes per events.

**Notification :**

- Event confirmation notification (Email / Text)
- Cancellation notification
- Reminder notification*
*(this might be difficult without a server)

**Comment by seakim** [comment]
changing the subject

**Comment by seakim** [comment]
###Lunch Finder
Lots of people do not like to think what to eat for lunch.  
2 ~ 3 or more APIs will be used:
1. API to get restaurant menu and price
2. Yelp to get restaurant info
3. API to get ingredient / calories / recipe 

1. The main functionality of this app is to give user a lunch recommendation near you.  When users put their budgets and what they want (trying to make it simple for users), it randomize the list of items and return it to users.
user input - what they want, how much money they want to spend, if they want delivery
output - 
* item name / picture / price + etc
* restaurant name / rate + etc
* distance from you / delivery option + etc
* couple yelp reviews

2. User can pick a item from the list, or get more items if not.

3. If user picked an item, it asks user to check the "general" information about the item such as ingredient / recipe / calories, and also asks if they want to rate the food or comment. (login will be needed).  User can use it as future reference if they want to have it again, and also it collect the detail user data about restaurant items (a micro Yelp? lol).

--- the main key that I think is to keep it fun and simple for users. --- sk

**Comment by seakim** [comment]
adding another feature idea -
Tinder for food.  User can swipe left and right if they like by looking at picture.
This gives user an idea of what they want to eat / and it's fun why not.
Also it let us collect user data.
